### ISSUE TITLE
Issues with crashing of large runs

### ISSUE THREAD

**Issue by Daafip** [Daafip/eWaterCycle-DA#31]
When computing a callibration run for an ensemble of 500 model runs, for several catchments seems to be a RAM issue. 
After two catchments (3 years each), on the third the run kills the terminal. Occured twice in testing.

- [x] investigate wether this is a WSL issue or an issue with the code 
- [x] Look into how to solve this
As it gets stuck in the update step: 
- [x] Gut feeling says its a dask issue, look into that
Still dask issue...:
- [x] Make dask fully optional (initially for local models)
     - advanced users can then still disable dask for containerised models by setting a bool between setup and initialize

**Comment by Daafip** [comment]
even with dask scheduler set to single-threaded still occurs

**Comment by Daafip** [comment]
Now testing if it occurs on SURF

**Comment by Daafip** [comment]
Looks to be a WSL problem, no real issue on when running on surf

**Comment by Daafip** [comment]
![Screenshot 2024-04-30 081754](https://github.com/Daafip/eWaterCycle-DA/assets/59128851/a55eb906-fa79-471f-8ece-3b626621e078)

**Comment by Daafip** [comment]
Get stuck in a update step likely, but could be difficult to debug where

**Comment by Daafip** [comment]
![image](https://github.com/Daafip/eWaterCycle-DA/assets/59128851/5431b1d8-da9a-4adf-a35a-3f61e8b40953)
(200 particles)

**Comment by Daafip** [comment]
> dask issue
Seems to somehow get stuck in the dask queue
Confirmed: 
![WhatsApp Image 2024-05-01 at 15 51 22_1f461f8c](https://github.com/Daafip/eWaterCycle-DA/assets/59128851/dfa63398-423f-4b1f-9b90-888320b03a01)

**Comment by Daafip** [comment]
Fix for now: 
make a non parrallel version for model names ending in "Local"

**Comment by Daafip** [comment]
still issue: 
```
70%|█████████████████████████████████████████████████▊                     | 791/1127 [53:14<22:36,  4.04s/it]Traceback (most recent call last):
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/Forcing/HBV_forcing_CAMELS_2024-05-02 12_37.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '3439265f-0156-411f-8b7d-1937b2cba6ba']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 249, in <module>
    main()
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 245, in main
    run(camels_forcing, HRU_id)
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 215, in run
    ds_summary = experiment_run(n_particles, p_max_initial, p_min_initial, s_0, model_name, camels_forcing,
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 142, in experiment_run
    ensemble.update(assimilate=assimilate)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 464, in update
    [self.update_linear(self, i) for i in range(self.N)]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 464, in <listcomp>
    [self.update_linear(self, i) for i in range(self.N)]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 492, in update_linear
    ensemble_member.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 881, in update
    self.model.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle/base/model.py", line 180, in update
    self._bmi.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_optionaldest.py", line 52, in update
    self.origin.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/HBV/HBV_bmi.py", line 115, in update
    self.Ep_dt = self.EP.isel(time=self.current_timestep).to_numpy() * self.dt
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/dataarray.py", line 786, in to_numpy
    return self.variable.to_numpy()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/variable.py", line 1091, in to_numpy
    return to_numpy(self._data)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/pycompat.py", line 114, in to_numpy
    data = data.get_duck_array()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 699, in get_duck_array
    self._ensure_cached()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 693, in _ensure_cached
    self.array = as_indexable(self.array.get_duck_array())
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 667, in get_duck_array
    return self.array.get_duck_array()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 554, in get_duck_array
    array = self.array[self.key]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 99, in __getitem__
    return indexing.explicit_indexing_adapter(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 861, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 111, in _getitem
    original_array = self.get_array(needs_lock=False)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 90, in get_array
    ds = self.datastore._acquire(needs_lock)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 410, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2492, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2009, in genexpr
  File "src/netCDF4/_netCDF4.pyx", line 2009, in genexpr
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/netCDF4/utils.py", line 32, in _find_dim
    def _find_dim(grp, dimname):
KeyboardInterrupt
```

**Comment by Daafip** [comment]
```
Traceback (most recent call last):
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/tqdm/std.py", line 1197, in __iter__
^CKeyboardInterrupt:
Traceback (most recent call last):
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/Forcing/HBV_forcing_CAMELS_2024-05-02 19_55.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), 'fce7e5ed-7a38-4afa-8a04-752f630265fb']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 271, in <module>
    main()
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 267, in main
    run(camels_forcing, HRU_id)
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 234, in run
    ds_summary = experiment_run(n_particles, p_max_initial, p_min_initial, s_0, model_name, camels_forcing,
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_33_run_all/33_run_all_camels.py", line 144, in experiment_run
    ensemble.update(assimilate=assimilate)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 464, in update
    [self.update_linear(self, i) for i in range(self.N)]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 464, in <listcomp>
    [self.update_linear(self, i) for i in range(self.N)]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 492, in update_linear
    ensemble_member.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 881, in update
    self.model.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle/base/model.py", line 180, in update
    self._bmi.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_optionaldest.py", line 52, in update
    self.origin.update()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/HBV/HBV_bmi.py", line 114, in update
    self.P_dt = self.P.isel(time=self.current_timestep).to_numpy() * self.dt
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/dataarray.py", line 786, in to_numpy
    return self.variable.to_numpy()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/variable.py", line 1091, in to_numpy
    return to_numpy(self._data)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/pycompat.py", line 114, in to_numpy
    data = data.get_duck_array()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 699, in get_duck_array
    self._ensure_cached()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 693, in _ensure_cached
    self.array = as_indexable(self.array.get_duck_array())
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 667, in get_duck_array
    return self.array.get_duck_array()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 554, in get_duck_array
    array = self.array[self.key]
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 99, in __getitem__
    return indexing.explicit_indexing_adapter(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 861, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 111, in _getitem
    original_array = self.get_array(needs_lock=False)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 90, in get_array
    ds = self.datastore._acquire(needs_lock)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 410, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2492, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2009, in genexpr
  File "src/netCDF4/_netCDF4.pyx", line 2009, in genexpr
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/netCDF4/utils.py", line 32, in _find_dim
    def _find_dim(grp, dimname):
KeyboardInterrupt
Killed
```

**Comment by Daafip** [comment]
And onther one, both on the isel section ofthe time. Maybe switch to loading the array at initialization as a numpy array

**Comment by Daafip** [comment]
Still memory issue (after around 9-12hrs of running). still in dask arrray: 
```
Traceback (most recent call last):
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/base.py", line 665, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/threaded.py", line 90, in get
    results = get_async(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/local.py", line 501, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/local.py", line 138, in queue_get
    return q.get()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/queue.py", line 171, in get
    self.not_empty.wait()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 296, in <module>
    main()
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 292, in main
    run(camels_forcing, HRU_id, sigma_p_Sf)
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 239, in run
    ds_summary = experiment_run(n_particles, p_max_initial, p_min_initial, s_0, model_name, camels_forcing,
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 70, in experiment_run
    ensemble.initialize(model_name=[model_name]*n_particles,
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 284, in initialize
    lst_models_name = gathered_initialize.compute(num_workers=1)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/base.py", line 379, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/base.py", line 664, in compute
    with shorten_traceback():
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/utils.py", line 2282, in __exit__
    exc_val.__traceback__ = self.shorten(exc_tb)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/dask/utils.py", line 2290, in shorten
    exp = re.compile(".*(" + "|".join(paths) + ")")
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_parse.py", line 841, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_parse.py", line 512, in _parse
    sourceget()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/sre_parse.py", line 255, in get
    def get(self):
KeyboardInterrupt
Killed
```
Seems to wait for a killed failed dask process.

- if local model: don't use dask...

**Comment by Daafip** [comment]
fixed in v 0.0.9: local models don't use parallelisation

**Comment by Daafip** [comment]
Add note in docs on when to and when not to parallelise

**Comment by Daafip** [comment]
Local model runs faster: but now quits on the third run, after initializing but before update: likely on initialize_ensemble_members_da
![image](https://github.com/Daafip/eWaterCycle-DA/assets/59128851/be8f1eb4-8bd2-47e7-a8d6-50964a2d032a)

**Comment by Daafip** [comment]
Looks like a memory issue, likely linked to WSL?

**Comment by Daafip** [comment]
![image](https://github.com/Daafip/eWaterCycle-DA/assets/59128851/d154e263-8281-4b0b-a90a-9e43d91c1b36)
memory usage just keeps climbin

**Comment by Daafip** [comment]
ile "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 300, in main
    run(camels_forcing, HRU_id, sigma_p_Sf)
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 245, in run
    ds_summary = experiment_run(n_particles, p_max_initial, p_min_initial, s_0, model_name, camels_forcing,
  File "/home/davidhaasnoot/eWaterCycle-WSL-WIP/nbs_34_run_lower_sf/34_run_diff_sig_p_s.py", line 70, in experiment_run
    ensemble.initialize(model_name=[model_name]*n_particles,
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 305, in initialize
    lst_models_name.append(self.initialize_run(self, i, custom_cfg_dir))
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 323, in initialize_run
    ensemble_member.initialize()
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_DA/DA.py", line 835, in initialize
    self.model.initialize(self.config)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle/base/model.py", line 168, in initialize
    self._bmi.initialize(config_file)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_optionaldest.py", line 49, in initialize
    return self.origin.initialize(config_file)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/HBV/HBV_bmi.py", line 53, in initialize
    self.ds_Tmean = utils.load_var(self.config["mean_temperature_file"], "tas")
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/HBV/utils.py", line 38, in load_var    data = xr.open_dataset(ncfile)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/api.py", line 572, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/netCDF4_.py", line 658, in open_dataset
    ds = store_entrypoint.open_dataset(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/backends/store.py", line 46, in open_dataset
    vars, attrs, coord_names = conventions.decode_cf_variables(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/conventions.py", line 436, in decode_cf_variables
    new_vars[k] = decode_cf_variable(
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/conventions.py", line 299, in decode_cf_variable
    if not is_duck_dask_array(data):
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/pycompat.py", line 98, in is_duck_dask_array
    return is_duck_array(x) and is_dask_collection(x)
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/utils.py", line 267, in is_duck_array
    and hasattr(value, "shape")
  File "/home/davidhaasnoot/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/xarray/core/indexing.py", line 548, in shape
    shape.append(len(range(*k.indices(size))))

Looks liek the isue is still there

**Comment by Daafip** [comment]
The roo Issue seems using the same forcing object, further discussion in #35
